[package]
name = "folder-watcher-and-app-launcher"
version = "0.1.0"
edition = "2021"
authors = ["Valeria Fadeeva <valeria@fadeeva.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "*"
notify = "*"
dotenv = "*"
